module.exports = {
  name: 'Mariusz Witkowski',
  email: 'mar.wit49@gmail.com',
  phone: '+48 609 289 604',
  github: 'https://github.com/MariuszWitkowski',
  linkedin: 'https://www.linkedin.com/in/mariusz-witkowski/',
  objective:
    'Senior frontend/fullstack developer with nine years of expertise in producing outstanding user interfaces and web apps. Devoted and accomplished. Looking to contribute to a dynamic team and lead the development of creative digital solutions by leveraging my knowledge of front-end technologies, excellent problem-solving skills, and leadership talents. committed to ensuring outstanding user experiences while being at the forefront of new web technologies.',
  qualifications: [
    'Over 9 years of experience in frontend/fullstack development.',
    'Proficient in TypeScript/JavaScript, HTML, CSS, and frontend frameworks',
    'Working in a large team with various departments as well as working independently from scratch to finish.',
    'Experience of working in SCRUM, Agile, Waterfall, and Kanban environments.',
  ],
  experience: [
    {
      title: 'Senior Frontend Developer',
      company: 'GogoApps',
      location: 'Warsaw, Poland',
      dates: '11/2020-Present',
      responsibilities: [
        'Creating greenfield projects',
        'Developing existing web and React Native applications',
        'Taking care of code quality by doing code reviews and creating tests',
        'Collaborated with UX/UI designers to create visually appealing',
        'CI/CD management',
      ],
    },
    {
      title: 'Full Stack Engineer',
      company: 'Teacode.io',
      location: 'Warsaw, Poland',
      dates: '09/2020-10/2020',
      responsibilities: [],
    },
    {
      title: 'Frontend Developer',
      company: 'Straal',
      location: 'Warsaw, Poland',
      dates: '04/2019-09/2020',
      responsibilities: [],
    },
    {
      title: 'Senior Frontend Developer',
      company: 'Grupa Wirtualna Polska',
      location: 'Warsaw, Poland',
      dates: '03/2016-03/2019',
      responsibilities: [],
    },
    {
      title: 'Programmer',
      company: 'Cadas Software',
      location: 'Warsaw, Poland',
      dates: '02/2014-02/2016',
      responsibilities: [],
    },
  ],
  education: {
    degree: 'Master of Sciences',
    university: 'SGGW',
    fieldOfStudy: 'Information Technology and Econometrics',
    graduationDate: '06/2015',
  },
  skills: [
    'Programming Languages: TypeScript/JavaScript, HTML, CSS, Python, Rust',
    'Frontend Frameworks: React, Vue.js, Angular.js, Angular, Svelte, Astro, 11ty',
    'Fullstack: Node.js, Next.js, Express.js, Nest.js',
    'Mobile: React Native, Flutter',
    'Testing: Jest, React Testing Library, Cypress, Playwright, Puppeteer',
    'Version Control: Git, Github, Gitlab, Bitbucket',
    'CI/CD: Github Actions, CircleCI, Jenkins, Gitlab CI',
    'Cloud: AWS, Azure',
    'Databases: MongoDB, PostgreSQL, MySQL, Firebase',
    'Other: Docker, Graphql, Webpack, NPM, Yarn, Bun, Vite, Storybook, Jira, Confluence, Trello, Slack, Notion, Figma,',
  ],
};
