module.exports = {
  name: 'Mariusz Witkowski',
  email: 'mar.wit49@gmail.com',
  phone: '+48 609 289 604',
  github: 'https://github.com/MariuszWitkowski',
  linkedin: 'https://www.linkedin.com/in/mariusz-witkowski/',
  cvPage: 'https://mariuszwitkowski.github.io/CV/',
  objective:
    'Senior frontend/fullstack developer with nine years of expertise in producing outstanding user interfaces and web apps. Devoted and accomplished. Looking to contribute to a dynamic team and lead the development of creative digital solutions by leveraging my knowledge of front-end technologies, excellent problem-solving skills, and leadership talents. committed to ensuring outstanding user experiences while being at the forefront of new web technologies.',
  explanation:
    'I wanted to create a minimalistic resume that is easy to read and navigate. I also wanted to make it easy to update and maintain. I used 11ty to generate the HTML from the data file. I used Github Pages to host the resume. I used Google Lighthouse to audit the resume. I used Google Mobile-Friendly Test to check if the resume is mobile-friendly.',
  qualifications: [
    'Over 9 years of experience in frontend/fullstack development.',
    'Proficient in TypeScript/JavaScript, HTML, CSS, and frontend frameworks.',
    'Working in a large team with various departments as well as working independently from scratch to finish.',
    'Experience of working in SCRUM, Agile, Waterfall, and Kanban environments.',
    'Implemented comprehensive unit and integration tests using Jest and Cypress to maintain code quality.',
    'Collaborated with UX designers to create intuitive user interfaces that enhance the user experience.',
    'Prioritized and managed tasks in Jira/ClickUp/Trello to ensure timely delivery of project milestones.',
    'Adaptability by quickly learning and adapting to new technologies and project requirements.',
    'Recruitment of frontend, React native and Node JS developers.',
    'Took on a leadership role as a mentor for junior/mid developers, fostering a collaborative and growth-oriented team culture.',
  ],
  experience: [
    {
      title: 'Senior Frontend Developer',
      company: 'GogoApps',
      location: 'Warsaw, Poland',
      dates: '11/2020-Present',
      responsibilities: [
        'Creating greenfield projects',
        'Developing existing web and React Native applications',
        'Taking care of code quality by doing code reviews and creating tests',
        'Collaborated with UX/UI designers to create visually appealing',
        'CI/CD management',
      ],
    },
    {
      title: 'Senior Frontend Developer',
      company: 'Esotiq',
      location: 'Warsaw, Poland',
      dates: '01/2023-present',
      responsibilities: [
        'A shopping basket for a stationary store in the React and the Electron',
        'Smooth transition animations between pages',
      ],
    },
    {
      title: 'Freelance',
      company: 'Side project',
      location: 'Warsaw, Poland',
      dates: '11/2022-05/2023',
      responsibilities: [
        'A domino game for learning musical notes in primary schools',
      ],
    },
    {
      title: 'Architect',
      company: 'Futbolkolektyw',
      location: 'Warsaw, Poland',
      dates: '09/2016-10/2021',
      responsibilities: [
        'Creating the entire project architecture from scratch',
        'Testing different solutions and methodologies to achieve the goal',
        'Dashboards for internal management, for closed users, as well as a panel with open registration',
        'Generator for scouts to create personalized player reports with the option of exporting to PDF',
        'CI/CD management',
        'Everything else that was required from a junior to a team leader',
      ],
    },
    {
      title: 'FullStack Engineer',
      company: 'Pick.Eat.Up',
      location: 'Warsaw, Poland',
      dates: '11/2020-06/2021',
      responsibilities: [
        'Creating API in Strapi',
        'Payments integration using Przelewy24',
        'Developing two React Native applications',
        'Admin panel in the Next.js',
      ],
    },
    {
      title: 'FullStack Engineer',
      company: 'Teacode.io',
      location: 'Warsaw, Poland',
      dates: '09/2020-10/2020',
      responsibilities: [
        'Creating API in feathers.js',
        'Developing greenfield React Native applications',
        'Building a dashboard for database management in the React-admin',
      ],
    },
    {
      title: 'Frontend Developer',
      company: 'Straal',
      location: 'Warsaw, Poland',
      dates: '04/2019-09/2020',
      responsibilities: [],
    },
    {
      title: 'Senior Frontend Developer',
      company: 'Grupa Wirtualna Polska',
      location: 'Warsaw, Poland',
      dates: '03/2016-03/2019',
      responsibilities: [],
    },
    {
      title: 'Programmer',
      company: 'Cadas Software',
      location: 'Warsaw, Poland',
      dates: '02/2014-02/2016',
      responsibilities: [],
    },
  ],
  education: {
    degree: 'Master of Sciences',
    university: 'SGGW',
    fieldOfStudy: 'Information Technology and Econometrics',
    graduationDate: '06/2015',
  },
  skills: [
    'Programming Languages: TypeScript/JavaScript, HTML, CSS, Python, Rust, Golang',
    'Frontend Frameworks: React, Vue.js, Angular.js, Angular, Svelte, Astro, 11ty, Gatsby',
    'Fullstack/Backend: Node.js, Next.js, Graphql, Express.js, Nest.js, Strapi, Feathers.js',
    'Mobile: React Native, Expo, Flutter',
    'State management: MobX, Zustand, Jotai, XState, Vuex, Redux',
    'Styling: Tailwind CSS, Styled Components, Sass, Less, Enzyme, Material UI, Semantic UI, Ant Design, Bootstrap',
    'Testing: Jest, React Testing Library, Cypress, Playwright, Puppeteer',
    'Version Control: Git, Github, Gitlab, Bitbucket',
    'CI/CD: Gitlab CI, Github Actions, CircleCI, Jenkins, Vercel',
    'Cloud: AWS, Azure, Firebase, Vercel',
    'Databases: MongoDB, PostgreSQL, Firebase, DynamoDB, SQLite',
    'Other: Docker, Storybook, RxJS, D3.js, Yarn, Bun, NPM, Vite, Webpack, Parcel, WebSockets, WebWorkers, i18n, MJML, Jira, ClickUp, Confluence, Trello, Slack, Discord, Notion, Figma, FeatureFlags, Recharts',
  ],
};
