module.exports = {
  name: 'Mariusz Witkowski',
  details: [
    {
      field: 'email',
      value: 'mar.wit49@gmail.com',
      href: 'mailto:mar.wit49@gmail.com',
    },
    { field: 'phone', value: '+48 609 289 604', href: 'tel:+48609289604' },
    { field: 'github', value: 'https://github.com/MariuszWitkowski' },
    {
      field: 'linkedin',
      value: 'https://www.linkedin.com/in/mariusz-witkowski/',
    },
    {
      field: 'X/Twitter',
      value: 'https://twitter.com/mwitkowski91',
    },
    {
      field: 'Interactive CV page',
      value: 'https://mariuszwitkowski.github.io/CV',
    },
  ],
  objective:
    'Senior frontend/fullstack developer with over nine years of expertise in producing outstanding user interfaces and web apps. Devoted and accomplished. Looking to contribute to a dynamic team and lead the development of creative digital solutions by leveraging my knowledge of front-end technologies, excellent problem-solving skills, and leadership talents. committed to ensuring outstanding user experiences while being at the forefront of new web technologies.',
  explanation:
    'I wanted to create a minimalistic resume that is easy to read and navigate. I also wanted to make it easy to update and maintain. I used 11ty to generate the HTML from the data file. I used Github Pages to host the resume. I used Google Lighthouse to audit the resume. I used Google Mobile-Friendly Test to check if the resume is mobile-friendly.',
  qualifications: [
    'Over 9 years of experience in frontend/fullstack development.',
    'Proficient in TypeScript/JavaScript, HTML, CSS, and frontend frameworks.',
    'Working in a large team with various departments as well as working independently from scratch to finish.',
    'Experience of working in SCRUM, Agile, Waterfall, and Kanban environments.',
    'Implemented comprehensive unit and integration tests using Jest and Cypress to maintain code quality.',
    'Collaborated with UX designers to create intuitive user interfaces that enhance the user experience.',
    'Prioritized and managed tasks in Jira/ClickUp/Trello to ensure timely delivery of project milestones.',
    'Adaptability by quickly learning and adapting to new technologies and project requirements.',
    'Recruitment of frontend, React native and Node JS developers.',
    'Took on a leadership role as a mentor for junior/mid developers, fostering a collaborative and growth-oriented team culture.',
    'Conducting lectures and programming classes for students.',
    'Experience in working with remote teams.',
  ],
  experience: [
    {
      title: 'Senior Frontend Developer',
      company: 'GogoApps',
      location: 'Warsaw, Poland',
      dates: '11/2020-Present',
      duration: '3 years',
      description:
        'Work in a full development multilingual teams as well as in solo projects. Outsourcing in various companies.',
      responsibilities: [
        'Creating greenfield projects',
        'Developing existing web and React Native applications',
        'Taking care of code quality by doing code reviews and creating tests',
        'Collaborated with UX/UI designers to create visually appealing',
        'Implement PWA-specific features, like service workers, to enable offline functionality, push notifications, and background syncing.',
        'Handle cross-browser compatibility issues.',
        'Keep the PWA up to date with the latest web standards and best practices.',
        'CI/CD management',
      ],
      usedTechnologies: [
        'TypeScript',
        'JavaScript',
        'React',
        'Angular',
        'Mobx',
        'zustand',
        'Redux',
        'Styled Components',
        'Tailwind CSS',
        'React Native',
        'Expo',
        'Node.js',
        'Nest.js',
        'PWA',
        'Jest',
        'Storybook',
        'Cypress',
        'Canvas',
        'capi',
        'React Query',
        'Agile',
        'Scrum',
        'Kanban',
        'and more',
      ],
    },
    {
      title: 'FullStack Engineer',
      company: 'Teacode.io',
      location: 'Warsaw, Poland',
      dates: '09/2020-10/2020',
      duration: '2 months',
      description:
        'Developing full-stack mobile applications on a custom backend in Nodejs, with database records management in the ReactAdmin dashboard',
      responsibilities: [
        'Creating API in feathers.js',
        'Developing greenfield React Native applications',
        'Building a dashboard for database management in the React-admin',
      ],
      usedTechnologies: [
        'TypeScript',
        'React',
        'ReactNative',
        'ReactAdmin',
        'Storybook',
        'Feathers.js',
        'Nodejs',
        'Mongodb',
      ],
    },
    {
      title: 'Frontend Developer',
      company: 'Straal',
      location: 'Warsaw, Poland',
      dates: '04/2019-09/2020',
      duration: '1 year 6 months',
      description:
        'Collaboration in the frontend team with a UX/UI designer and backend developers.',
      responsibilities: [
        'Creating dashboard for managing users, transactions, subscriptions',
        'Visualizing statistics on charts',
        'Creating unit tests in TDD and e2e in Cypress',
        'Conducting lectures and programming classes for students',
        'Implement service workers and integrate with push notifications',
      ],
      usedTechnologies: [
        'Vue',
        'RxJs',
        'TypeScript',
        'Graphql',
        'D3js',
        'Cypress',
        'Jest',
        'NodeJS',
        'Storybook',
        'AWS',
      ],
    },
    {
      title: 'Senior Frontend Developer',
      company: 'Grupa Wirtualna Polska',
      location: 'Warsaw, Poland',
      dates: '03/2016-03/2019',
      duration: '3 years',
      description:
        'Developing E-mail interface on one of the most popular websites in Poland with cooperating with UX/UI designers and backend developers.',
      responsibilities: [
        'Developing E-mail interface on one of the most popular websites in Poland',
        'Rewriting whole application from AngularJS to React',
        'Building Help page for mail (TypeScript, Next.js, React, Node.js)',
        'Developing Mail user profile (React, MobX)',
        'Currently payment panel and the ability to purchase mail to pro version (React, MobX, Node.js)',
        'Working in Agile, Scrum',
      ],
      usedTechnologies: [
        'TypeScript',
        'AngularJS',
        'React',
        'Sass',
        'NextJS',
        'NodeJS',
        'Mobx',
        'Storybook',
        'BEM',
      ],
    },
    {
      title: 'Programmer',
      company: 'Cadas Software',
      location: 'Warsaw, Poland',
      dates: '02/2014-02/2016',
      duration: '2 years',
      description:
        'Developing application for creating surveys, managing dashboards and database',
      responsibilities: [],
      usedTechnologies: ['ExtJS', 'Java', 'Postgresql'],
    },
  ],
  freelance: [
    {
      title: 'Senior Frontend Developer',
      company: 'Esotiq',
      location: 'Warsaw, Poland',
      dates: '01/2023-present',
      duration: '10 months',
      description: 'Creating a shopping cart application for a smart store',
      responsibilities: [
        'A shopping basket for a stationary store in the React and the Electron',
        'Smooth transition animations between pages',
      ],
      usedTechnologies: [
        'TypeScript',
        'React',
        'Zustand',
        'React Router',
        'ReactQuery',
        'Electron',
      ],
    },
    {
      title: 'Game developer',
      company: 'Side project',
      location: 'Warsaw, Poland',
      dates: '01/2023-03/2023',
      duration: '2 months',
      description:
        'A domino game for learning musical notes in primary schools',
      usedTechnologies: [
        'React',
        'Zustand',
        'Tailwind CSS',
        'Storybook',
        'Pnpm',
        'Vite',
      ],
    },
    {
      title: 'Architect',
      company: 'Futbolkolektyw',
      location: 'Warsaw, Poland',
      dates: '09/2016-10/2021',
      duration: '5 years',
      description:
        'Doing everything that was required from a junior to a team leader. A lot of experimenting with modern solutions.',
      responsibilities: [
        'Creating the entire project architecture from scratch',
        'Testing different solutions and methodologies to achieve the goal',
        'Dashboards for internal management, for closed users, as well as a panel with open registration',
        'Generator for scouts to create personalized player reports with the option of exporting to PDF',
        'Using PWA features to enable offline functionality,  push notifications',
        'CI/CD management',
      ],
      usedTechnologies: [
        'TypeScript',
        'React',
        'ReactNative',
        'Next.js',
        'Node.js',
        'Express.js',
        'PWA',
        'Storybook',
        'MongoDB',
        'Docker',
        'AWS',
        'and more',
      ],
    },
    {
      title: 'FullStack Engineer',
      company: 'Pick.Eat.Up',
      location: 'Warsaw, Poland',
      dates: '11/2020-06/2021',
      duration: '8 months',
      description:
        'Creating an application that helps the environment and can prevent food waste',
      responsibilities: [
        'Creating API in Strapi',
        'Payments integration using Przelewy24',
        'Developing two React Native applications',
        'Admin panel in the Next.js',
      ],
      usedTechnologies: [
        'TypeScript',
        'React',
        'ReactNative',
        'Strapi',
        'Next.js',
        'Styled Components',
      ],
    },
  ],
  education: {
    degree: 'Master of Sciences',
    university: 'Szkoła Główna Gospodarstwa Wiejskiego in Warsaw',
    fieldOfStudy: 'Information Technology and Econometrics',
    graduationDate: '06/2015',
  },
  skills: [
    {
      label: 'Programming Languages',
      values: [
        'TypeScript/JavaScript',
        'HTML',
        'CSS',
        'Python',
        'Rust',
        'Golang',
      ],
    },
    {
      label: 'Frontend Frameworks',
      values: [
        'React',
        'Vue.js',
        'Angular.js',
        'Angular',
        'Svelte',
        'Astro',
        '11ty',
        'Gatsby',
      ],
    },
    {
      label: 'Fullstack/Backend',
      values: [
        'Node.js',
        'Next.js',
        'Graphql',
        'Express.js',
        'Nest.js',
        'Strapi',
        'Feathers.js',
      ],
    },
    {
      label: 'Mobile',
      values: ['React Native', 'Expo', 'Flutter', 'Fastlane'],
    },
    {
      label: 'State management',
      values: ['MobX', 'Zustand', 'Jotai', 'XState', 'Vuex', 'Redux'],
    },
    {
      label: 'Styling',
      values: [
        'Tailwind CSS',
        'Styled Components',
        'Sass',
        'Less',
        'Enzyme',
        'Material UI',
        'Semantic UI',
        'Ant Design',
        'Bootstrap',
      ],
    },
    {
      label: 'Visualization',
      values: ['Nivo', 'D3.js', 'Recharts', 'Chart.js', 'Highcharts'],
    },
    {
      label: 'Animations',
      values: ['Framer Motion', 'React Spring', 'Lottie'],
    },
    {
      label: 'Testing',
      values: [
        'Jest',
        'React Testing Library',
        'Cypress',
        'Mocha',
        'Puppeteer',
        'Playwright',
      ],
    },
    {
      label: 'Version Control',
      values: ['Git', 'Conventional Commits', 'Github', 'Gitlab', 'Bitbucket'],
    },
    {
      label: 'CI/CD',
      values: ['Gitlab CI', 'Github Actions', 'CircleCI', 'Jenkins', 'Vercel'],
    },
    { label: 'Cloud', values: ['AWS', 'Azure', 'Firebase', 'Vercel'] },
    {
      label: 'Databases',
      values: ['MongoDB', 'PostgreSQL', 'Firebase', 'SQLite', 'DynamoDB'],
    },
    {
      label: 'Management',
      values: [
        'Jira',
        'ClickUp',
        'Trello',
        'Slack',
        'Discord',
        'Notion',
        'Confluence',
      ],
    },
    {
      label: 'Other',
      values: [
        'PWA',
        'Docker',
        'Storybook',
        'RxJS',
        'ReactQuery',
        'Zod',
        'Yarn',
        'Bun',
        'Deno',
        'NPM',
        'Vite',
        'Pnpm',
        'Electron',
        'Webpack',
        'Parcel',
        'WebSockets',
        'WebWorkers',
        'i18n',
        'MJML',
        'Figma',
        'FeatureFlags',
      ],
    },
  ],
  coreSkills: [
    'TypeScript',
    'React',
    'HTML5/CSS3',
    'Jest',
    'Git',
    'Problem solving',
  ],
};
